// Text receipt (layout-spec Text variant) in BOTH v1 locales, resolving the
// real generated catalogs so the receipt is proven fully localized.

import hi from '../messages/hi.json';
import en from '../messages/en.json';
import { buildTextReceipt } from '@/lib/invoice/receipt';
import type { InvoiceData, InvoiceLabels } from '@/lib/invoice/types';

type Catalog = typeof en;

function labelsFrom(catalog: Catalog): InvoiceLabels {
  const inv = catalog.invoice;
  return {
    title: inv.title,
    numberLabel: inv.number_label,
    issueDateLabel: inv.issue_date_label,
    billedTo: inv.billed_to,
    eventLabel: inv.event_label,
    totalAmount: inv.total_amount,
    securityDeposit: inv.security_deposit,
    paymentHistory: inv.payment_history,
    tableDate: inv.table.date,
    tableMethod: inv.table.method,
    tableNotes: inv.table.notes,
    tableAmount: inv.table.amount,
    totalPaid: inv.total_paid,
    balanceDue: inv.balance_due,
    fullyPaid: inv.fully_paid,
    noPayments: inv.no_payments,
    footer: inv.footer,
  };
}

function sampleData(catalog: Catalog): InvoiceData {
  return {
    businessName: 'Shree Ganesh Hall',
    businessType: 'Marriage Hall',
    address: null,
    ownerName: 'Suresh Gupta',
    invoiceNumber: 'SGH-2026-0042',
    issueDate: '2026-07-15',
    customerName: 'Ramesh Kumar',
    customerPhone: '9876543210',
    eventIcon: '\u{1F492}',
    eventLabel: catalog.booking.event_type.wedding,
    startDate: '2026-07-10',
    endDate: '2026-07-12',
    startTime: null,
    endTime: null,
    totalAmount: 106511,
    securityDeposit: 5000,
    payments: [
      { paidOn: '2026-07-01', methodLabel: catalog.invoice.method.cash, notes: null, amount: 50000 },
      { paidOn: '2026-07-11', methodLabel: catalog.invoice.method.upi, notes: 'ref 812', amount: 6511 },
    ],
  };
}

describe('buildTextReceipt (en)', () => {
  const receipt = buildTextReceipt(sampleData(en), labelsFrom(en), 'en');

  it('mirrors the invoice order: business, number, customer, event, amounts, payments', () => {
    const lines = receipt.split('\n');
    expect(lines[0]).toBe('Shree Ganesh Hall');
    expect(lines[1]).toContain('SGH-2026-0042');
    expect(receipt.indexOf('Ramesh Kumar')).toBeLessThan(receipt.indexOf('Total amount'));
    expect(receipt.indexOf('Total amount')).toBeLessThan(receipt.indexOf('Payment history'));
    expect(receipt.trim().endsWith('Generated by Samaroh')).toBe(true);
  });

  it('uses Indian digit grouping and shows the outstanding due', () => {
    expect(receipt).toContain('Total amount: \u20B91,06,511');
    expect(receipt).toContain('Security deposit: \u20B95,000');
    expect(receipt).toContain('Total paid: \u20B956,511');
    expect(receipt).toContain('Balance due: \u20B950,000');
  });

  it('lists one line per payment with localized method labels', () => {
    expect(receipt).toContain('Cash');
    expect(receipt).toContain('UPI');
    expect(receipt).toContain('\u20B950,000');
    expect(receipt).toContain('\u20B96,511');
    expect(receipt).toContain('ref 812');
  });

  it('marks fully-paid receipts instead of a due amount', () => {
    const data = sampleData(en);
    data.payments = [{ paidOn: '2026-07-01', methodLabel: en.invoice.method.cash, notes: null, amount: 106511 }];
    const paidReceipt = buildTextReceipt(data, labelsFrom(en), 'en');
    expect(paidReceipt).toContain(en.invoice.fully_paid);
    expect(paidReceipt).toContain('Balance due: \u20B90');
  });

  it('omits the security deposit line when the deposit is zero', () => {
    const data = sampleData(en);
    data.securityDeposit = 0;
    expect(buildTextReceipt(data, labelsFrom(en), 'en')).not.toContain('Security deposit');
  });
});

describe('buildTextReceipt (hi)', () => {
  const receipt = buildTextReceipt(sampleData(hi), labelsFrom(hi), 'hi');

  it('renders Hindi labels from the catalog with the same ₹ formatting', () => {
    expect(receipt).toContain(hi.invoice.total_amount);
    expect(receipt).toContain(hi.invoice.balance_due);
    expect(receipt).toContain(hi.invoice.footer);
    expect(receipt).toContain('\u20B91,06,511');
  });

  it('uses the localized event-type and method labels', () => {
    expect(receipt).toContain(hi.booking.event_type.wedding);
    expect(receipt).toContain(hi.invoice.method.cash);
    expect(receipt).toContain(hi.invoice.method.upi);
  });

  it('contains no untranslated English invoice labels', () => {
    expect(receipt).not.toContain('Total amount');
    expect(receipt).not.toContain('Balance due');
    expect(receipt).not.toContain('Generated by');
  });
});
